#!/usr/bin/env node

/**
 * Sandcastle Runner - Node.js wrapper for executing sandcastle runs.
 * Called by the Python backend via subprocess.
 * 
 * Supports:
 * - Single agent runs
 * - Multi-agent parallel execution
 * - Structured output extraction
 * - Real-time log streaming via stdout
 */

import { parseArgs } from "node:util";
import { readFileSync, writeFileSync, mkdirSync, mkdtempSync, chmodSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { tmpdir } from "node:os";
import { resolve, dirname, join } from "node:path";

// Parse command line arguments
const { values } = parseArgs({
  options: {
    config: { type: "string" },
    "run-id": { type: "string" },
    mode: { type: "string", default: "single" }, // single | parallel
  },
  strict: false,
});

if (!values.config) {
  console.error("Error: --config argument is required");
  process.exit(1);
}

// Read configuration
const configPath = resolve(values.config);
const config = JSON.parse(readFileSync(configPath, "utf-8"));

// Cancellation: the Python backend terminates this process (via its process group)
// to cancel/timeout a run. Translating SIGTERM/SIGINT into an AbortSignal lets
// sandcastle's run() tear the container down gracefully instead of leaking it.
const abortController = new AbortController();
for (const sig of ["SIGTERM", "SIGINT"]) {
  process.on(sig, () => abortController.abort(new Error(`received ${sig}`)));
}

// The sandcastle docker/podman providers only expose `cpus` and `network`
// natively — they own the `docker run` invocation and give us no hook for
// --memory / --pids-limit / --read-only. To enforce those we drop a tiny wrapper
// script named exactly like the runtime binary ("docker" / "podman") onto the
// front of PATH; it splices the extra flags into `run` sub-commands and passes
// everything else (exec/ps/rm/build/inspect) straight through to the real
// binary. Installed once per runtime, and only when flags are actually set — so
// with no hardening configured PATH is untouched and behaviour is unchanged.
const _shimmedRuntimes = new Set();

function installRuntimeShim(runtime, extraRunFlags) {
  if (!extraRunFlags || extraRunFlags.length === 0) return;
  if (_shimmedRuntimes.has(runtime)) return;

  // Resolve the real binary BEFORE we touch PATH, so the shim never recurses.
  // runtime is always "docker"/"podman" here — no shell-injection surface.
  let realBinary;
  try {
    realBinary = execFileSync("/bin/sh", ["-c", `command -v ${runtime}`], {
      encoding: "utf-8",
    }).trim();
  } catch {
    console.error(`Warning: could not resolve '${runtime}' binary; skipping resource-cap shim.`);
    return;
  }
  if (!realBinary) {
    console.error(`Warning: '${runtime}' not found on PATH; skipping resource-cap shim.`);
    return;
  }

  const shimDir = mkdtempSync(join(tmpdir(), `sandcastle-shim-${runtime}-`));
  const shimPath = join(shimDir, runtime);
  const quoted = extraRunFlags.map((f) => `'${String(f).replace(/'/g, "'\\''")}'`).join(" ");
  const script = `#!/bin/sh
# Auto-generated by sandcastle_runner.mjs — injects resource/security caps into 'run'.
if [ "$1" = "run" ]; then
  shift
  exec ${realBinary} run ${quoted} "$@"
fi
exec ${realBinary} "$@"
`;
  writeFileSync(shimPath, script);
  chmodSync(shimPath, 0o755);
  process.env.PATH = `${shimDir}:${process.env.PATH || ""}`;
  _shimmedRuntimes.add(runtime);
  console.error(`Installed ${runtime} resource-cap shim: ${quoted}`);
}

// Collect the resource/network caps the Python bridge threaded into the run
// config into the shape createSandboxProvider expects.
function securityFromConfig(config) {
  return {
    cpus: typeof config.cpu_quota === "number" ? config.cpu_quota : undefined,
    network: config.network || undefined,
    containerRunFlags: config.container_run_flags || [],
  };
}

// Helper to create sandbox provider
async function createSandboxProvider(providerType, dockerImage, security = {}) {
  // Auto-mount Claude credentials for subscription-based auth. Note: this gives the
  // sandboxed agent your Claude account token; the secure compose keeps the agent on
  // an isolated network to limit exfiltration risk.
  const claudeHome = process.env.HOME;
  const mounts = [];
  if (claudeHome) {
    const credentialsPath = `${claudeHome}/.claude/.credentials.json`;
    try {
      const { accessSync } = await import("node:fs");
      accessSync(credentialsPath);
      mounts.push({
        hostPath: credentialsPath,
        sandboxPath: "/home/agent/.claude/.credentials.json",
        readonly: true,
      });
    } catch {
      // No credentials file found — will fail with "not logged in"
    }
  } else {
    console.error("Warning: HOME is unset; skipping Claude credentials mount.");
  }

  // Native provider options (only cpus + network are supported by the library);
  // the rest of the caps go through the PATH shim installed below.
  const providerOpts = { imageName: dockerImage, mounts };
  if (typeof security.cpus === "number") providerOpts.cpus = security.cpus;
  if (security.network) providerOpts.network = security.network;

  switch (providerType) {
    case "docker": {
      installRuntimeShim("docker", security.containerRunFlags);
      const { docker } = await import("@ai-hero/sandcastle/sandboxes/docker");
      return docker(providerOpts);
    }
    case "podman": {
      installRuntimeShim("podman", security.containerRunFlags);
      const { podman } = await import("@ai-hero/sandcastle/sandboxes/podman");
      return podman(providerOpts);
    }
    case "vercel": {
      const { vercel } = await import("@ai-hero/sandcastle/sandboxes/vercel");
      return vercel();
    }
    case "no-sandbox":
    default: {
      const { noSandbox } = await import("@ai-hero/sandcastle/sandboxes/no-sandbox");
      return noSandbox();
    }
  }
}

// Helper to create agent provider
// Maps Claude Cockpit provider IDs to sandcastle library factories
async function createAgentProvider(sandcastle, providerType, options = {}) {
  const model = options.model || "sonnet";
  switch (providerType) {
    case "claude-code": {
      const { claudeCode } = sandcastle;
      return claudeCode(model, options);
    }
    case "codex-cli": {
      const { codex } = sandcastle;
      return codex(model, options);
    }
    case "open-code": {
      const { opencode } = sandcastle;
      return opencode(model, options);
    }
    case "mimo-code": {
      throw new Error(
        "mimo-code is not supported in sandbox mode — the container only has claude-code installed. " +
        "Switch agent_provider to 'claude-code' for sandbox runs."
      );
    }
    default: {
      throw new Error(
        `Unknown agent provider '${providerType}'. ` +
        `Supported providers: claude-code, codex-cli, open-code`
      );
    }
  }
}

// Execute a single run
async function executeRun(sandcastle, config, runConfig) {
  const { run } = sandcastle;
  
  const sandboxProvider = await createSandboxProvider(
    config.sandbox_provider,
    config.docker_image,
    securityFromConfig(config)
  );

  const agentOptions = {};
  if (config.model) {
    agentOptions.model = config.model;
  } else {
    agentOptions.model = "sonnet";
  }
  
  const agentProvider = await createAgentProvider(
    sandcastle,
    config.agent_provider,
    agentOptions
  );
  
  const runOptions = {
    agent: agentProvider,
    sandbox: sandboxProvider,
    prompt: runConfig.prompt,
    maxIterations: config.max_iterations || 1,
    idleTimeoutSeconds: config.idle_timeout_seconds || 600,
    signal: abortController.signal,
  };
  
  // Add branch strategy if specified
  if (runConfig.branch_name) {
    runOptions.branchStrategy = {
      type: "branch",
      branch: runConfig.branch_name,
    };
  } else if (config.branch_strategy) {
    runOptions.branchStrategy = { type: config.branch_strategy };
  }
  
  // Add logging to file
  const logDir = resolve(config.project_path, ".sandcastle", "logs");
  mkdirSync(logDir, { recursive: true });
  const logFile = resolve(logDir, `run-${runConfig.run_id || Date.now()}.log`);
  
  runOptions.logging = {
    type: "file",
    path: logFile,
    verbose: true,
  };
  
  // Add structured output if specified
  if (runConfig.output_schema) {
    const { Output } = sandcastle;
    runOptions.output = Output.object({
      tag: runConfig.output_tag || "result",
      schema: runConfig.output_schema,
    });
  }
  
  // Execute the run
  const result = await run(runOptions);
  
  return {
    iterations: result.iterations?.length || 0,
    commits: result.commits || [],
    branch: result.branch || null,
    completionSignal: result.completionSignal || null,
    output: result.output || null,
    logFile,
  };
}

// Execute parallel runs
async function executeParallelRuns(sandcastle, config, runs) {
  const { run } = sandcastle;
  
  // Create shared sandbox if requested
  if (config.use_shared_sandbox) {
    const { createSandbox } = sandcastle;
    const sandboxProvider = await createSandboxProvider(
      config.sandbox_provider,
      config.docker_image,
      securityFromConfig(config)
    );
    
    const agentOptions = {};
    if (config.model) {
      agentOptions.model = config.model;
    } else {
      agentOptions.model = "sonnet";
    }
    
    const agentProvider = await createAgentProvider(
      sandcastle,
      config.agent_provider,
      agentOptions
    );
    
    const sandbox = await createSandbox({
      branch: config.shared_branch || "agent/parallel",
      sandbox: sandboxProvider,
    });
    
    try {
      // Execute all runs on the same sandbox
      const results = [];
      for (const runConfig of runs) {
        const result = await sandbox.run({
          agent: agentProvider,
          prompt: runConfig.prompt,
          maxIterations: config.max_iterations || 1,
          signal: abortController.signal,
        });
        results.push({
          run_id: runConfig.run_id,
          iterations: result.iterations?.length || 0,
          commits: result.commits || [],
          branch: result.branch || null,
        });
      }
      
      return { mode: "shared-sandbox", results };
    } finally {
      if (typeof sandbox[Symbol.asyncDispose] === "function") {
        await sandbox[Symbol.asyncDispose]();
      } else if (typeof sandbox.close === "function") {
        await sandbox.close();
      } else if (typeof sandbox.destroy === "function") {
        await sandbox.destroy();
      }
    }
  }
  
  // Execute runs in parallel on separate sandboxes
  const promises = runs.map(async (runConfig) => {
    try {
      const result = await executeRun(sandcastle, config, runConfig);
      return { run_id: runConfig.run_id, ...result, status: "completed" };
    } catch (error) {
      return {
        run_id: runConfig.run_id,
        status: "failed",
        error: error.message,
      };
    }
  });
  
  const results = await Promise.allSettled(promises);
  return {
    mode: "parallel",
    results: results.map((r) => r.status === "fulfilled" ? r.value : r.reason),
  };
}

async function main() {
  try {
    // Dynamically import sandcastle
    const sandcastle = await import("@ai-hero/sandcastle");
    
    console.error("Sandcastle config:", JSON.stringify(config, null, 2));

    // Ensure run_id is set so the log filename matches the path the backend records
    // (it falls back to Date.now() otherwise, and the backend can never find the log).
    if (config.run_id == null && values["run-id"] != null) {
      config.run_id = values["run-id"];
    }

    let output;

    if (values.mode === "parallel" && config.runs) {
      // Multi-agent parallel execution
      output = await executeParallelRuns(sandcastle, config, config.runs);
    } else {
      // Single run
      output = await executeRun(sandcastle, config, config);
    }
    
    // Output result as JSON
    console.log(JSON.stringify(output));
    process.exit(0);
  } catch (error) {
    console.error("Sandcastle run failed:", error.message);
    console.error("Stack:", error.stack);
    process.exit(1);
  }
}

main();