"""drop removed agent-mail message tables

Revision ID: 6f3b196b3680
Revises: e2fa1bd8f45d
Create Date: 2026-08-15

De berichten-, mailbox- en receipt-laag van Agent Mail is verwijderd in commit
97e821fc (kaart 46930d26). De modellen verdwenen, de tabellen bleven -- er was
nog geen migratie toen die refactor landde. Deze revisie maakt het schema
gelijk aan de modellen.

Alle drie de tabellen waren leeg op de live registry-database toen dit werd
geschreven, dus er gaat geen gegeven verloren. De roster-laag (MailTeamMember)
blijft ongemoeid; die hield zijn gewicht wel.

SQLite kan geen kolom wijzigen, vandaar batch_alter_table.
"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

revision = '6f3b196b3680'
down_revision = 'e2fa1bd8f45d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mail_external_actors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mail_external_actors_actor_key'))

    op.drop_table('mail_external_actors')
    with op.batch_alter_table('mail_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mail_messages_created_at'))
        batch_op.drop_index(batch_op.f('ix_mail_messages_kind'))
        batch_op.drop_index(batch_op.f('ix_mail_messages_recipient_member_id'))
        batch_op.drop_index(batch_op.f('ix_mail_messages_request_status'))
        batch_op.drop_index(batch_op.f('ix_mail_messages_thread_root_id'))

    op.drop_table('mail_messages')
    with op.batch_alter_table('mail_receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mail_receipts_member_id'))
        batch_op.drop_index(batch_op.f('ix_mail_receipts_message_id'))

    op.drop_table('mail_receipts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mail_receipts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('message_id', sa.INTEGER(), nullable=False),
    sa.Column('member_id', sa.INTEGER(), nullable=False),
    sa.Column('read_at', sa.DATETIME(), nullable=True),
    sa.Column('acked_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['mail_team_members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['mail_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'member_id', name=op.f('uix_mail_receipt_message_member'))
    )
    with op.batch_alter_table('mail_receipts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mail_receipts_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mail_receipts_member_id'), ['member_id'], unique=False)

    op.create_table('mail_messages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('thread_root_id', sa.INTEGER(), nullable=True),
    sa.Column('kind', sa.VARCHAR(length=24), nullable=False),
    sa.Column('sender_member_id', sa.INTEGER(), nullable=True),
    sa.Column('sender_actor_id', sa.INTEGER(), nullable=True),
    sa.Column('recipient_member_id', sa.INTEGER(), nullable=True),
    sa.Column('subject', sa.VARCHAR(length=512), nullable=True),
    sa.Column('body_markdown', sa.TEXT(), nullable=False),
    sa.Column('payload', sqlite.JSON(), nullable=True),
    sa.Column('request_status', sa.VARCHAR(length=16), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_member_id'], ['mail_team_members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_actor_id'], ['mail_external_actors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sender_member_id'], ['mail_team_members.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['thread_root_id'], ['mail_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mail_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mail_messages_thread_root_id'), ['thread_root_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mail_messages_request_status'), ['request_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_mail_messages_recipient_member_id'), ['recipient_member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mail_messages_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_mail_messages_created_at'), ['created_at'], unique=False)

    op.create_table('mail_external_actors',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('actor_key', sa.VARCHAR(length=80), nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=256), nullable=False),
    sa.Column('kind', sa.VARCHAR(length=80), nullable=False),
    sa.Column('description', sa.VARCHAR(length=512), nullable=True),
    sa.Column('token_hash', sa.VARCHAR(length=64), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('last_used_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mail_external_actors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mail_external_actors_actor_key'), ['actor_key'], unique=1)

    # ### end Alembic commands ###
