"""baseline registry schema

Revision ID: a31f18593f46
Revises: 
Create Date: 2026-08-15 14:31:43.659560

SQLite cannot ALTER a column. Any change to an existing column MUST go through
`with op.batch_alter_table("<table>") as batch_op:` — a plain op.alter_column
will fail at runtime on both of this project's stores.
"""
import sqlalchemy as sa
from alembic import op

revision = 'a31f18593f46'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_path', sa.String(length=1024), nullable=False),
    sa.Column('instance_id', sa.String(length=16), nullable=False),
    sa.Column('command', sa.JSON(), nullable=False),
    sa.Column('env_keys', sa.JSON(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=256), nullable=False),
    sa.Column('health_path', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('transport', sa.String(length=16), nullable=False),
    sa.Column('container_id', sa.String(length=64), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('log_path', sa.String(length=512), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_runs_instance_id'), ['instance_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_app_runs_project_path'), ['project_path'], unique=False)

    op.create_table('auto_backup_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('project_path', sa.String(), nullable=True),
    sa.Column('time_of_day', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(), nullable=True),
    sa.Column('last_backup_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bridge_session_attachments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('session_name', sa.String(), nullable=True),
    sa.Column('cli', sa.String(), nullable=True),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('agent_path', sa.String(), nullable=False),
    sa.Column('prompt_text', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bridge_session_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bridge_session_attachments_sha256'), ['sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_bridge_session_attachments_target'), ['target'], unique=False)

    op.create_table('hosts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('hostname', sa.String(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('ssh_key_path', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hosts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hosts_alias'), ['alias'], unique=True)

    op.create_table('mail_external_actors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_key', sa.String(length=80), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('kind', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mail_external_actors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mail_external_actors_actor_key'), ['actor_key'], unique=True)

    op.create_table('mail_team_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('identity_key', sa.String(length=64), nullable=False),
    sa.Column('repo_id', sa.String(length=32), nullable=False),
    sa.Column('repo_path', sa.String(length=1024), nullable=False),
    sa.Column('repo_name', sa.String(length=256), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=128), nullable=True),
    sa.Column('charter', sa.Text(), nullable=True),
    sa.Column('last_inbox_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mail_team_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mail_team_members_identity_key'), ['identity_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_mail_team_members_repo_id'), ['repo_id'], unique=False)

    op.create_table('marketplaces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('last_synced', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('mcp_access_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token_prefix', sa.String(length=16), nullable=False),
    sa.Column('token_hash', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('agent_name', sa.String(length=128), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mcp_access_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mcp_access_tokens_token_prefix'), ['token_prefix'], unique=True)

    op.create_table('mcp_server_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('server_name', sa.String(), nullable=False),
    sa.Column('server_scope', sa.String(), nullable=False),
    sa.Column('is_connected', sa.Boolean(), nullable=False),
    sa.Column('last_tested_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('mcp_server_name', sa.String(), nullable=True),
    sa.Column('mcp_server_version', sa.String(), nullable=True),
    sa.Column('tools', sa.JSON(), nullable=True),
    sa.Column('tool_count', sa.Integer(), nullable=False),
    sa.Column('resources', sa.JSON(), nullable=True),
    sa.Column('prompts', sa.JSON(), nullable=True),
    sa.Column('resource_count', sa.Integer(), nullable=False),
    sa.Column('prompt_count', sa.Integer(), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=True),
    sa.Column('cached_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('config_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_name', 'server_scope', name='uix_server_name_scope')
    )
    with op.batch_alter_table('mcp_server_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mcp_server_cache_server_name'), ['server_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_server_cache_server_scope'), ['server_scope'], unique=False)

    op.create_table('presence_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('project_path', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('status_text', sa.String(), nullable=True),
    sa.Column('last_narrative', sa.String(), nullable=True),
    sa.Column('last_narrative_at', sa.DateTime(), nullable=True),
    sa.Column('modified_files', sa.JSON(), nullable=True),
    sa.Column('last_command', sa.String(), nullable=True),
    sa.Column('last_command_exit', sa.Integer(), nullable=True),
    sa.Column('activity_buckets', sa.JSON(), nullable=True),
    sa.Column('bucket_start', sa.DateTime(), nullable=True),
    sa.Column('total_events', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('last_event_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('last_user_prompt', sa.String(), nullable=True),
    sa.Column('tmux_pane', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('presence_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_presence_sessions_last_event_at'), ['last_event_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_presence_sessions_session_id'), ['session_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_presence_sessions_status'), ['status'], unique=False)

    op.create_table('project_security_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_path', sa.String(), nullable=False),
    sa.Column('risk_class', sa.String(), server_default='product-staging', nullable=False),
    sa.Column('default_transport', sa.String(), server_default='sandcastle', nullable=False),
    sa.Column('default_skip_permissions', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('secrets_scope_id', sa.String(), nullable=True),
    sa.Column('resource_quota', sa.JSON(), nullable=False),
    sa.Column('network_policy', sa.String(), server_default='allowlist', nullable=False),
    sa.Column('egress_allowlist', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_security_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_security_profiles_project_path'), ['project_path'], unique=True)

    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('kind', sa.String(), server_default='product', nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('last_accessed', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    op.create_table('recurring_triggers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_key', sa.String(length=512), nullable=False),
    sa.Column('cron_expr', sa.String(length=120), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('work_type', sa.String(length=16), nullable=True),
    sa.Column('agent', sa.String(length=64), nullable=True),
    sa.Column('labels', sa.JSON(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('last_fired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recurring_triggers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recurring_triggers_project_key'), ['project_key'], unique=False)

    op.create_table('run_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lead_run_name', sa.String(), nullable=True),
    sa.Column('cli', sa.String(), nullable=False),
    sa.Column('cwd', sa.String(), nullable=False),
    sa.Column('is_auto_detected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sandcastle_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_path', sa.String(length=1024), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('sandbox_provider', sa.String(length=32), nullable=False),
    sa.Column('agent_provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('branch_strategy', sa.String(length=32), nullable=False),
    sa.Column('docker_image', sa.String(length=256), nullable=True),
    sa.Column('max_iterations', sa.Integer(), nullable=False),
    sa.Column('idle_timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('permission_mode', sa.String(length=32), nullable=False),
    sa.Column('memory_limit_mb', sa.Integer(), nullable=True),
    sa.Column('cpu_quota', sa.Float(), nullable=True),
    sa.Column('pids_limit', sa.Integer(), nullable=True),
    sa.Column('read_only_rootfs', sa.Boolean(), nullable=False),
    sa.Column('network_mode', sa.String(length=16), nullable=False),
    sa.Column('egress_allowlist', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sandcastle_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sandcastle_configs_project_path'), ['project_path'], unique=True)

    op.create_table('security_audit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('project_key', sa.String(length=512), nullable=False),
    sa.Column('actor', sa.String(length=256), nullable=False),
    sa.Column('payload_ref', sa.JSON(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('security_audit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_security_audit_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_audit_kind'), ['kind'], unique=False)
        batch_op.create_index('ix_security_audit_project_at', ['project_key', 'at'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_audit_project_key'), ['project_key'], unique=False)

    op.create_table('session_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('project_folder', sa.String(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('total_messages', sa.Integer(), nullable=False),
    sa.Column('total_tool_calls', sa.Integer(), nullable=False),
    sa.Column('cached_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_cache_project_folder'), ['project_folder'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_cache_session_id'), ['session_id'], unique=True)

    op.create_table('subscription_prefs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('anthropic_plan_tier', sa.String(), nullable=True),
    sa.Column('anthropic_custom_limit_tokens', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usage_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cache_key', sa.String(), nullable=False),
    sa.Column('cache_type', sa.String(), nullable=False),
    sa.Column('project_path', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('cached_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usage_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_cache_cache_key'), ['cache_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_usage_cache_cache_type'), ['cache_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_cache_project_path'), ['project_path'], unique=False)

    op.create_table('backups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('is_automatic', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mail_agent_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('cli', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('session_key', sa.String(length=256), nullable=False),
    sa.Column('cwd', sa.String(length=1024), nullable=True),
    sa.Column('tmux_target', sa.String(length=128), nullable=True),
    sa.Column('pane_id', sa.String(length=64), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('mailbox_status', sa.String(length=16), nullable=False),
    sa.Column('activity', sa.String(length=256), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['mail_team_members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mail_agent_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mail_agent_sessions_last_seen_at'), ['last_seen_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_mail_agent_sessions_member_id'), ['member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mail_agent_sessions_session_key'), ['session_key'], unique=True)

    op.create_table('mail_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('thread_root_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('sender_member_id', sa.Integer(), nullable=True),
    sa.Column('sender_actor_id', sa.Integer(), nullable=True),
    sa.Column('recipient_member_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=512), nullable=True),
    sa.Column('body_markdown', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('request_status', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recipient_member_id'], ['mail_team_members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_actor_id'], ['mail_external_actors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sender_member_id'], ['mail_team_members.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['thread_root_id'], ['mail_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mail_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mail_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_mail_messages_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_mail_messages_recipient_member_id'), ['recipient_member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mail_messages_request_status'), ['request_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_mail_messages_thread_root_id'), ['thread_root_id'], unique=False)

    op.create_table('presence_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('tool_name', sa.String(), nullable=True),
    sa.Column('tool_input', sa.JSON(), nullable=True),
    sa.Column('tool_result', sa.JSON(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('cwd', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['presence_sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('presence_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_presence_events_session_id'), ['session_id'], unique=False)

    op.create_table('run_memberships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('run_name', sa.String(), nullable=False),
    sa.Column('pane_id', sa.String(), nullable=True),
    sa.Column('tmux_target', sa.String(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['run_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sandcastle_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_path', sa.String(length=1024), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('branch', sa.String(length=256), nullable=True),
    sa.Column('commits', sa.JSON(), nullable=True),
    sa.Column('stdout', sa.Text(), nullable=True),
    sa.Column('stderr', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('log_file_path', sa.String(length=512), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['sandcastle_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sandcastle_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sandcastle_runs_project_path'), ['project_path'], unique=False)

    op.create_table('mail_receipts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['mail_team_members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['mail_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'member_id', name='uix_mail_receipt_message_member')
    )
    with op.batch_alter_table('mail_receipts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mail_receipts_member_id'), ['member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mail_receipts_message_id'), ['message_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mail_receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mail_receipts_message_id'))
        batch_op.drop_index(batch_op.f('ix_mail_receipts_member_id'))

    op.drop_table('mail_receipts')
    with op.batch_alter_table('sandcastle_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sandcastle_runs_project_path'))

    op.drop_table('sandcastle_runs')
    op.drop_table('run_memberships')
    with op.batch_alter_table('presence_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_presence_events_session_id'))

    op.drop_table('presence_events')
    with op.batch_alter_table('mail_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mail_messages_thread_root_id'))
        batch_op.drop_index(batch_op.f('ix_mail_messages_request_status'))
        batch_op.drop_index(batch_op.f('ix_mail_messages_recipient_member_id'))
        batch_op.drop_index(batch_op.f('ix_mail_messages_kind'))
        batch_op.drop_index(batch_op.f('ix_mail_messages_created_at'))

    op.drop_table('mail_messages')
    with op.batch_alter_table('mail_agent_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mail_agent_sessions_session_key'))
        batch_op.drop_index(batch_op.f('ix_mail_agent_sessions_member_id'))
        batch_op.drop_index(batch_op.f('ix_mail_agent_sessions_last_seen_at'))

    op.drop_table('mail_agent_sessions')
    op.drop_table('backups')
    with op.batch_alter_table('usage_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_cache_project_path'))
        batch_op.drop_index(batch_op.f('ix_usage_cache_cache_type'))
        batch_op.drop_index(batch_op.f('ix_usage_cache_cache_key'))

    op.drop_table('usage_cache')
    op.drop_table('subscription_prefs')
    with op.batch_alter_table('session_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_cache_session_id'))
        batch_op.drop_index(batch_op.f('ix_session_cache_project_folder'))

    op.drop_table('session_cache')
    with op.batch_alter_table('security_audit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_security_audit_project_key'))
        batch_op.drop_index('ix_security_audit_project_at')
        batch_op.drop_index(batch_op.f('ix_security_audit_kind'))
        batch_op.drop_index(batch_op.f('ix_security_audit_at'))

    op.drop_table('security_audit')
    with op.batch_alter_table('sandcastle_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sandcastle_configs_project_path'))

    op.drop_table('sandcastle_configs')
    op.drop_table('run_groups')
    with op.batch_alter_table('recurring_triggers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recurring_triggers_project_key'))

    op.drop_table('recurring_triggers')
    op.drop_table('projects')
    with op.batch_alter_table('project_security_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_security_profiles_project_path'))

    op.drop_table('project_security_profiles')
    with op.batch_alter_table('presence_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_presence_sessions_status'))
        batch_op.drop_index(batch_op.f('ix_presence_sessions_session_id'))
        batch_op.drop_index(batch_op.f('ix_presence_sessions_last_event_at'))

    op.drop_table('presence_sessions')
    with op.batch_alter_table('mcp_server_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mcp_server_cache_server_scope'))
        batch_op.drop_index(batch_op.f('ix_mcp_server_cache_server_name'))

    op.drop_table('mcp_server_cache')
    with op.batch_alter_table('mcp_access_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mcp_access_tokens_token_prefix'))

    op.drop_table('mcp_access_tokens')
    op.drop_table('marketplaces')
    with op.batch_alter_table('mail_team_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mail_team_members_repo_id'))
        batch_op.drop_index(batch_op.f('ix_mail_team_members_identity_key'))

    op.drop_table('mail_team_members')
    with op.batch_alter_table('mail_external_actors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mail_external_actors_actor_key'))

    op.drop_table('mail_external_actors')
    with op.batch_alter_table('hosts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hosts_alias'))

    op.drop_table('hosts')
    with op.batch_alter_table('bridge_session_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bridge_session_attachments_target'))
        batch_op.drop_index(batch_op.f('ix_bridge_session_attachments_sha256'))

    op.drop_table('bridge_session_attachments')
    op.drop_table('auto_backup_settings')
    with op.batch_alter_table('app_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_runs_project_path'))
        batch_op.drop_index(batch_op.f('ix_app_runs_instance_id'))

    op.drop_table('app_runs')
    # ### end Alembic commands ###
