"""add auto_resume_configs

Revision ID: b015af7f5f1b
Revises: 6f3b196b3680
Create Date: 2026-08-16 10:16:54.483668

SQLite cannot ALTER a column. Any change to an existing column MUST go through
`with op.batch_alter_table("<table>") as batch_op:` — a plain op.alter_column
will fail at runtime on both of this project's stores.
"""
import sqlalchemy as sa
from alembic import op

revision = 'b015af7f5f1b'
down_revision = '6f3b196b3680'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Voorwaardelijk, en dat is hier geen overdaad. `init_db` roept nog steeds
    # `Base.metadata.create_all` aan, en dat maakt ELKE ontbrekende tabel aan --
    # ook een die een nog niet gedraaide revisie hoort te maken. Draait de app
    # dus een keer voordat je migreert, dan bestaat de tabel al en faalt een
    # kale create_table met "table already exists". Gemeten op de live
    # registry-database, 2026-08-16.
    if "auto_resume_configs" in sa.inspect(op.get_bind()).get_table_names():
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto_resume_configs',
    sa.Column('cwd', sa.String(length=1024), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('cwd')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auto_resume_configs')
    # ### end Alembic commands ###
