"""Worktree-local RTK (token-saver) installer.

Opt-in, fail-open, board kill-switchable. The helper is the dispatcher-side
seam of kaart ``c31333bf…`` and
``docs/superpowers/specs/2026-07-24-token-saver-integration-design.md``.

Public surface:

- :func:`maybe_install` — dispatcher-facing entry point. Never raises.
  Returns ``(status, reason)`` where ``status`` is one of
  ``"active" | "inactive" | "failed"``.
- :func:`is_board_enabled` / :func:`set_board_enabled` — the per-project
  runtime kill-switch, backed by ``KanbanMeta``.
- :func:`post_note` — activity-feed comment with 60s dedup so a backlog
  flush does not flood the feed with one ``Token saver …`` note per
  card.
- :func:`write_rtk_settings_into_worktree` — the filesystem step in
  isolation, exposed for the measurement harness so the harness exercises
  the *exact* same JSON-merge code path the dispatcher does.

Fail-open contract: every step wraps a guarded try/except and degrades
to ``("failed", "<reason>")`` rather than re-raising. The dispatcher
catches ``(status, reason)`` and continues the spawn unchanged.
"""
from __future__ import annotations

import json
import os
import shutil
import stat
import tempfile
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from sqlalchemy import select

from app.kanban.models import KanbanColumn, KanbanMeta, KanbanOp

# Pinned RTK release. Single source of truth — bump here when the project
# decides to upgrade. Mirrors docs/cockpit/token-saver-mechanismen-decision.md §8
# (versie-pinnen verplicht; het project shipt RC's in een tempo dat
# auto-update onverantwoord maakt).
RTK_PINNED_VERSION = "0.43.0"

# Cache layout — per-user (under $HOME), per-version. Layout under this
# directory:
#   bin/rtk               — pinned RTK binary, executable
#   hooks/rtk-rewrite.sh  — pinned upstream rewrite hook, read-only after install
RTK_CACHE_ROOT = Path(
    os.environ.get(
        "COCKPIT_RTK_CACHE_ROOT",
        f"{os.environ.get('HOME', '/root')}/.local/share/cockpit/rtk",
    )
)

# Default dedup window for the activity-feed ``**Note:** Token saver …``
# comment. Sized so a backlog flush running multiple cards within seconds
# collapses to one note per dispatch tick, not one per card. Tests can
# monkeypatch this to 0 to verify the dedup branch deterministically.
_DEDUP_WINDOW_SECONDS = 60

# Activity-feed prefix. Deliberately distinct from every other consumer
# prefix in docs/cockpit/kanban-conventions.md §2 (``**Summary:**`` /
# ``**Impediment:**`` / ``**Resolution:**`` / ``**Revisit:**`` /
# ``**Review requested:**``). Operator grep for ``Token saver`` lands on
# exactly these comments.
_NOTE_PREFIX = "**Note:** Token saver"

# Wrapper hook script body — small enough to inline so the worktree
# bootstrap is one filesystem write. Responsibilities:
#   1. Bypass ``git diff`` rewriting (lossy on shipping lanes; see
#      docs/cockpit/token-saver-mechanismen-decision.md §4.1.3).
#   2. Bypass bare ``grep`` without ``-r`` (host ``grep`` is ugrep which
#      recurses; RTK invokes GNU grep which fails on directory args —
#      see §4.1.4).
#   3. Delegate the rewrite to the pinned upstream script.
#   4. Exit 0 on any failure (Claude Code requirement for PreToolUse).
_HOOK_SCRIPT_BODY = f"""#!/usr/bin/env bash
# Auto-generated by Cockpit token-saver integration (kaart c31333bf…).
# Do not edit by hand — re-running `maybe_install` regenerates this file.
# Source: hooks/claude/rtk-rewrite.sh from rtk-ai/rtk v{RTK_PINNED_VERSION}.
set -e
INPUT="$(cat)"
CMD="$(printf '%s' "$INPUT" | jq -r '.tool_input.command // empty' 2>/dev/null || true)"
if [ -z "$CMD" ]; then exit 0; fi
# Bypass: bare `grep` without -r/--recursive on directory args.
# (RTK's grep rewriter shells to GNU grep, which dies on a directory
# arg; this host's grep is ugrep, which silently recurses. Bypassing
# the rewrite preserves the host's behaviour.)
case "$CMD" in
  grep*)
    if echo "$CMD" | grep -Eq -- ' (-r|-R|--recursive)( |$)'; then
      : # recursion flag present — let RTK handle it
    else
      exit 0
    fi
    ;;
esac
# Bypass: `git diff` (lossy on shipping lanes — see decision doc §4.1.3).
case "$CMD" in
  'git diff'*|'git' 'diff'*|*"git diff"*)
    exit 0
    ;;
esac
# Delegate to the pinned upstream rewrite script.
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
exec "$SCRIPT_DIR/rtk-rewrite.sh" <<<"$INPUT"
"""


# ---------------------------------------------------------------------------
# Public surface
# ---------------------------------------------------------------------------


async def is_board_enabled(session, project_key: str) -> bool:
    """Whether the per-project runtime kill-switch is on.

    Reads the ``token_saver:<project_key>`` row from ``KanbanMeta`` and
    treats only the literal string ``"1"`` as on. Anything else
    (``"0"``, absent row, ``"yes"``, …) → ``False``. The dispatch hot
    path calls this on every tick so a flipped switch takes effect on
    the next dispatch without a backend restart.
    """
    if not project_key:
        return False
    row = (await session.execute(
        select(KanbanMeta).where(KanbanMeta.key == f"token_saver:{project_key}")
    )).scalar_one_or_none()
    return bool(row and row.value == "1")


async def set_board_enabled(session, project_key: str, enabled: bool) -> None:
    """Persist the per-project runtime kill-switch.

    Idempotent. Writes ``"1"`` or ``"0"`` matching the convention used
    by ``set_autodispatch`` / ``set_skip_permissions``: read the row,
    update value or insert. The KanbanMeta table is device-local (not
    op-log-backed), so no audit comment is posted — operators flip the
    toggle in the UI, not via dispatch.
    """
    key = f"token_saver:{project_key}"
    row = await session.get(KanbanMeta, key)
    if row is None:
        row = KanbanMeta(key=key, value="1" if enabled else "0")
        session.add(row)
    else:
        row.value = "1" if enabled else "0"
    await session.flush()


async def post_note(session, card_id: str, text: str) -> None:
    """Post a ``**Note:** Token saver …`` audit comment to a card's op-log.

    Dedup: if the most recent matching comment on this card landed
    within :data:`_DEDUP_WINDOW_SECONDS`, the new comment is suppressed.
    The dedup is per-card and per-prefix so a separate state-change on
    the same card (e.g. dispatch failure) is never silenced.
    """
    from app.kanban.operations import apply_operation

    full_text = f"{_NOTE_PREFIX}{text[len(_NOTE_PREFIX):] if text.startswith(_NOTE_PREFIX) else ': ' + text}"
    # Normalise: callers pass the *reason*; we always prepend the canonical
    # prefix. The dedup scan matches on the prefix so a re-post within the
    # window collapses to nothing.
    if not text.startswith(_NOTE_PREFIX):
        full_text = f"{_NOTE_PREFIX}: {text}"

    last = (await session.execute(
        select(KanbanOp)
        .where(KanbanOp.entity_id == card_id)
        .where(KanbanOp.op_type == "comment")
        .order_by(KanbanOp.hlc.desc())
        .limit(20)  # narrow scan; op-log has all history but we only need the tail
    )).scalars().all()

    now = datetime.now(UTC)
    for op in last:
        payload_text = (op.payload or {}).get("text", "")
        if not payload_text.startswith(_NOTE_PREFIX):
            continue
        try:
            # SQLite strips tzinfo; reattach UTC before subtracting.
            created = op.created_at
            if created.tzinfo is None:
                created = created.replace(tzinfo=UTC)
            age = (now - created).total_seconds()
        except Exception:
            continue
        if age < _DEDUP_WINDOW_SECONDS:
            return  # suppressed — within the dedup window

    await apply_operation(
        session, op_type="comment", entity_type="comment",
        project_key="", entity_id=card_id,
        payload={"text": full_text},
    )


async def maybe_install(
    session, *,
    card_id: str,
    project_key: str,
    column_name: str,
    worktree_path: str,
    repo_path: str,
) -> tuple[str, str]:
    """Decide whether to install RTK for this dispatch, and do it.

    Returns ``(status, reason)`` where ``status`` is one of:

    - ``"active"`` — wrapper hook + settings.json patched; spawn should
      carry ``RTK_TELEMETRY=off``.
    - ``"inactive"`` — per-lane flag or kill-switch off; no filesystem
      writes.
    - ``"failed"`` — attempted but couldn't install (RTK missing, wrong
      version, settings unwriteable, etc.); dispatch continues unchanged.

    Never raises. The dispatcher relies on this guarantee: a buggy
    helper must not crash the spawn hot path.
    """
    try:
        return await _maybe_install_impl(
            session, card_id=card_id, project_key=project_key,
            column_name=column_name,
            worktree_path=worktree_path, repo_path=repo_path,
        )
    except Exception as exc:  # pragma: no cover — defensive
        return ("failed", f"{type(exc).__name__}: {exc}")


async def _maybe_install_impl(
    session, *,
    card_id: str,
    project_key: str,
    column_name: str,
    worktree_path: str,
    repo_path: str,
) -> tuple[str, str]:
    # Per-lane opt-in.
    col = (await session.execute(
        select(KanbanColumn).where(
            KanbanColumn.project_key == project_key,
            KanbanColumn.name == column_name,
        )
    )).scalar_one_or_none()
    if col is None or not getattr(col, "token_saver_enabled", 0):
        return ("inactive", "per-lane flag off")

    # Board kill-switch.
    if not await is_board_enabled(session, project_key):
        return ("inactive", "board kill-switch off")

    # Worktree exists.
    wt = Path(worktree_path)
    if not wt.is_dir():
        return ("failed", f"worktree not found: {worktree_path}")

    # Locate RTK.
    binary = _resolve_rtk_binary()
    if binary is None:
        return ("failed", "rtk binary missing")

    # Verify version.
    ok, version = _verify_rtk_version(binary)
    if not ok:
        return ("failed", f"rtk version {version} (need >= {RTK_PINNED_VERSION})")

    # Best-effort cache bootstrap (idempotent; no-op on a fully-cached box).
    try:
        _ensure_cache_ready()
    except Exception:
        pass  # already fail-open at every step

    # Write the wrapper hook + patch settings.json.
    write_rtk_settings_into_worktree(str(wt), binary)
    return ("active", f"RTK {RTK_PINNED_VERSION}")


# ---------------------------------------------------------------------------
# Filesystem steps — exposed for the measurement harness so the harness
# exercises the *exact* same code path the dispatcher does.
# ---------------------------------------------------------------------------


def write_rtk_settings_into_worktree(worktree_path: str, rtk_binary: str) -> None:
    """Materialise the wrapper hook into the RTK cache and patch
    ``.claude/settings.local.json``.

    Why two moves and not one:

    - **Wrapper hook in the cache** (``<cache>/<version>/hooks/``):
      the wrapper is a plain shell script, identical across every worktree
      on this host, and writing it into the worktree would create an
      untracked ``.claude/hooks/`` directory — the ship-gate's
      ``git ls-files --others --exclude-standard`` step would abort on
      that from the first second of every dispatch
      (``docs/cockpit/kanban-conventions.md`` §2 + ``git-ship`` SKILL §3).
      Putting it in the per-version cache means every worktree on this
      host shares one copy, no untracked files appear, and the cache
      bootstrap (best-effort) brings it in alongside the upstream
      ``rtk-rewrite.sh`` it delegates to.

    - **Settings in ``.claude/settings.local.json``** (NOT
      ``settings.json``): the tracked ``settings.json`` is shared repo
      state; patching it would create a modified file in every dispatch
      worktree, again tripping the ship-gate's pre-flight
      ``git diff --quiet HEAD --`` check. Claude Code's default gitignore
      covers ``**/.claude/settings.local.json``
      (``~/.config/git/ignore:1``), so the file is invisible to ``git``
      entirely and the worktree stays clean. The Bash PreToolUse command
      we write there points at the absolute cache path so the hook runs
      regardless of which worktree it is invoked from.

    Idempotent. Preserves every other key in the existing
    ``settings.local.json``. Raises on filesystem failure — the
    dispatcher wrapper at :func:`maybe_install` catches the raise and
    converts to ``("failed", "<reason>")`` so a broken filesystem never
    breaks a dispatch.
    """
    wt = Path(worktree_path)
    if not wt.is_dir():
        raise FileNotFoundError(f"worktree not found: {worktree_path}")

    # Wrapper script lives in the RTK cache, OUTSIDE the worktree. The
    # cache dir is per-version, parallel to ``bin/rtk`` and
    # ``hooks/rtk-rewrite.sh`` (the upstream script we delegate to).
    wrapper = _ensure_wrapper_in_cache()

    # Patch settings.local.json — the gitignored overlay Claude Code reads
    # on top of the tracked settings.json. Absolute path to the wrapper
    # so the hook works from any worktree on this host.
    settings_path = wt / ".claude" / "settings.local.json"
    payload = _load_or_default_settings(settings_path)
    _merge_rtk_hook(payload, wrapper_path=str(wrapper))
    _atomic_write_json(settings_path, payload)


def _wrapper_cache_path() -> Path:
    """Absolute path of the wrapper script under the pinned cache dir."""
    return (
        RTK_CACHE_ROOT / RTK_PINNED_VERSION / "hooks"
        / "rtk-cockpit-rewrite-wrapper.sh"
    )


def _ensure_wrapper_in_cache() -> Path:
    """Materialise the wrapper script in the pinned cache dir, idempotent.

    Returns the absolute path. The cache layout mirrors the upstream
    RTK cache: ``<cache>/<version>/{bin,hooks}/``. Upstream ships
    ``hooks/rtk-rewrite.sh``; we add ``hooks/rtk-cockpit-rewrite-wrapper.sh``
    alongside it. Both scripts end up co-located so the wrapper's
    ``$(dirname "$0")/rtk-rewrite.sh`` lookup works without an absolute
    path.
    """
    wrapper = _wrapper_cache_path()
    if not wrapper.exists():
        wrapper.parent.mkdir(parents=True, exist_ok=True)
        wrapper.write_text(_HOOK_SCRIPT_BODY)
    _make_executable(wrapper)
    return wrapper


def _merge_rtk_hook(payload: dict[str, Any], wrapper_path: str) -> None:
    """Append the Bash PreToolUse entry pointing at ``wrapper_path``,
    idempotently."""
    hooks = payload.setdefault("hooks", {})
    pretooluse = hooks.setdefault("PreToolUse", [])
    target = str(wrapper_path)
    for entry in pretooluse:
        if entry.get("matcher") != "Bash":
            continue
        for h in entry.get("hooks", []):
            if h.get("type") == "command" and target in h.get("command", ""):
                return  # already merged
    pretooluse.append({
        "matcher": "Bash",
        "hooks": [{
            "type": "command",
            "command": target,
        }],
    })


def _load_or_default_settings(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    raw = path.read_text()
    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        # Caller (write_rtk_settings_into_worktree) treats JSON-parse
        # failure as a hard error so the original file is not silently
        # overwritten. We re-raise here so the outer caller sees it.
        raise


def _atomic_write_json(path: Path, data: dict[str, Any]) -> None:
    """Write JSON atomically (tmp + os.replace) so a crash mid-write
    cannot corrupt an existing ``settings.json``.

    Mirrors the pattern in ``api.v1.kanban.router._write_json_atomic``.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(
        prefix=f".{path.name}.", suffix=".tmp", dir=str(path.parent),
    )
    try:
        with os.fdopen(fd, "w") as fh:
            json.dump(data, fh, indent=2)
        os.replace(tmp_name, path)
    except Exception:
        try:
            os.unlink(tmp_name)
        except OSError:
            pass
        raise


def _make_executable(path: Path) -> None:
    mode = path.stat().st_mode
    path.chmod(mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)


# ---------------------------------------------------------------------------
# Bootstrap / cache (best-effort; safe to skip silently)
# ---------------------------------------------------------------------------


def _resolve_rtk_binary() -> str | None:
    """Find the pinned RTK binary.

    Order:
      1. ``$COCKPIT_RTK_BIN`` env override (operator ad-hoc testing).
      2. The cache directory at :data:`RTK_CACHE_ROOT`.
      3. ``shutil.which("rtk")`` (PATH lookup).

    Returns the absolute path or ``None``. Never raises — a path that
    fails the version check is treated as "not found".
    """
    override = os.environ.get("COCKPIT_RTK_BIN")
    if override and Path(override).is_file():
        return override

    cached = _resolve_cache_binary()
    if cached is not None:
        return cached

    return shutil.which("rtk")


def _resolve_cache_binary() -> str | None:
    """Return the cached pinned binary or ``None`` if not present."""
    p = RTK_CACHE_ROOT / RTK_PINNED_VERSION / "bin" / "rtk"
    return str(p) if p.is_file() else None


def _verify_rtk_version(binary: str) -> tuple[bool, str]:
    """Run ``<binary> --version`` and check the first token starts with
    the pinned version. Returns ``(ok, version)``.

    Anything other than ``"0.43.0[.x]"`` → ``ok=False``. This is the
    "no silent fallback" contract: a too-old binary on PATH must not
    look like a working install.
    """
    import subprocess
    try:
        out = subprocess.run(
            [binary, "--version"], capture_output=True, text=True,
            timeout=5, check=False,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        return (False, f"unreachable: {type(exc).__name__}")
    text = (out.stdout or out.stderr or "").strip()
    # The pinned binary prints "rtk 0.43.0" — first token after `rtk `.
    parts = text.split()
    version = parts[1] if len(parts) >= 2 and parts[0] == "rtk" else text
    if version.startswith(RTK_PINNED_VERSION + ".") or version == RTK_PINNED_VERSION:
        return (True, version)
    return (False, version or "unknown")


def _ensure_cache_ready() -> None:
    """Best-effort cache bootstrap. No-op when the cache already has the
    pinned binary; otherwise tries one sync download from
    ``rtk-ai/rtk@v<RTK_PINNED_VERSION>`` with a 5s timeout. Never raises.

    Out-of-band bootstrap via ``scripts/install-rtk.sh`` (a follow-up
    card) is the air-gap path; this helper is for the connected case.
    """
    if _resolve_cache_binary() is not None:
        return  # cache hit — nothing to do

    cache_dir = RTK_CACHE_ROOT / RTK_PINNED_VERSION
    bin_dir = cache_dir / "bin"
    hooks_dir = cache_dir / "hooks"
    bin_dir.mkdir(parents=True, exist_ok=True)
    hooks_dir.mkdir(parents=True, exist_ok=True)

    import subprocess
    base = (
        f"https://raw.githubusercontent.com/rtk-ai/rtk/"
        f"v{RTK_PINNED_VERSION}"
    )
    for relpath, dest in (
        ("hooks/claude/rtk-rewrite.sh", hooks_dir / "rtk-rewrite.sh"),
    ):
        if dest.is_file():
            continue
        try:
            subprocess.run(
                ["curl", "-fsSL", "--max-time", "5", f"{base}/{relpath}",
                 "-o", str(dest)],
                check=True, capture_output=True, timeout=10,
            )
            _make_executable(dest)
        except (OSError, subprocess.SubprocessError, subprocess.TimeoutExpired):
            return  # best-effort; do not raise
