"""baseline board schema

Revision ID: c18135689409
Revises: 
Create Date: 2026-08-15 14:31:43.994159

SQLite cannot ALTER a column. Any change to an existing column MUST go through
`with op.batch_alter_table("<table>") as batch_op:` — a plain op.alter_column
will fail at runtime on both of this project's stores.
"""
import sqlalchemy as sa
from alembic import op

revision = 'c18135689409'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kanban_cards',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_key', sa.String(length=512), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('column', sa.String(length=32), nullable=False),
    sa.Column('rank', sa.String(length=64), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=True),
    sa.Column('labels', sa.JSON(), nullable=True),
    sa.Column('work_type', sa.String(length=16), nullable=True),
    sa.Column('agent', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('column_overrides', sa.JSON(), nullable=True),
    sa.Column('transport', sa.String(length=16), nullable=True),
    sa.Column('resume_session_id', sa.String(length=256), nullable=True),
    sa.Column('resume_project_folder', sa.String(length=512), nullable=True),
    sa.Column('scheduled_at', sa.String(length=40), nullable=True),
    sa.Column('dispatch_started_at', sa.String(length=40), nullable=True),
    sa.Column('dispatch_session_id', sa.String(length=64), nullable=True),
    sa.Column('pending_spawn_session', sa.String(length=64), nullable=True),
    sa.Column('dispatch_project_folder', sa.String(length=512), nullable=True),
    sa.Column('dispatch_model', sa.String(length=64), nullable=True),
    sa.Column('dispatch_provider', sa.String(length=32), nullable=True),
    sa.Column('analyst_agent_id', sa.String(length=64), nullable=True),
    sa.Column('executor_agent_id', sa.String(length=64), nullable=True),
    sa.Column('parent_card_id', sa.String(length=64), nullable=True),
    sa.Column('analyst_run_id', sa.String(length=64), nullable=True),
    sa.Column('depends_on', sa.JSON(), nullable=True),
    sa.Column('held_reason', sa.String(length=32), nullable=True),
    sa.Column('held_since', sa.String(length=40), nullable=True),
    sa.Column('held_blocker', sa.JSON(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('dispatch_failures', sa.Integer(), nullable=False),
    sa.Column('release_without_terminal_move', sa.Integer(), nullable=False),
    sa.Column('claimed_by', sa.String(length=256), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title_hlc', sa.String(length=48), nullable=True),
    sa.Column('description_hlc', sa.String(length=48), nullable=True),
    sa.Column('column_hlc', sa.String(length=48), nullable=True),
    sa.Column('rank_hlc', sa.String(length=48), nullable=True),
    sa.Column('claim_hlc', sa.String(length=48), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kanban_cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kanban_cards_parent_card_id'), ['parent_card_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kanban_cards_project_key'), ['project_key'], unique=False)

    op.create_table('kanban_columns',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_key', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('rank', sa.String(length=64), nullable=False),
    sa.Column('default_agent', sa.String(length=64), nullable=True),
    sa.Column('default_provider', sa.String(length=16), nullable=True),
    sa.Column('default_model', sa.String(length=64), nullable=True),
    sa.Column('max_sessions', sa.Integer(), nullable=True),
    sa.Column('token_saver_enabled', sa.Integer(), nullable=False),
    sa.Column('caveman_enabled', sa.Integer(), nullable=False),
    sa.Column('ponytail_enabled', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kanban_columns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kanban_columns_project_key'), ['project_key'], unique=False)

    op.create_table('kanban_meta',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('kanban_ops',
    sa.Column('op_id', sa.String(length=128), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('hlc', sa.String(length=48), nullable=False),
    sa.Column('project_key', sa.String(length=512), nullable=False),
    sa.Column('entity_type', sa.String(length=16), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('op_type', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('op_id')
    )
    with op.batch_alter_table('kanban_ops', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kanban_ops_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kanban_ops_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kanban_ops_hlc'), ['hlc'], unique=False)
        batch_op.create_index(batch_op.f('ix_kanban_ops_project_key'), ['project_key'], unique=False)

    op.create_table('kanban_work_type_mappings',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_key', sa.String(length=512), nullable=False),
    sa.Column('work_type', sa.String(length=32), nullable=False),
    sa.Column('persona', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_key', 'work_type', name='uq_kanban_work_type_mappings_project_work_type')
    )
    with op.batch_alter_table('kanban_work_type_mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kanban_work_type_mappings_project_key'), ['project_key'], unique=False)

    op.create_table('kanban_attachments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('card_id', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['kanban_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kanban_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kanban_attachments_card_id'), ['card_id'], unique=False)

    op.create_table('kanban_deliverables',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('card_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('ref', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['kanban_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kanban_deliverables', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kanban_deliverables_card_id'), ['card_id'], unique=False)

    op.create_table('kanban_gates',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('card_id', sa.String(length=64), nullable=False),
    sa.Column('project_key', sa.String(length=512), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['kanban_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kanban_gates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kanban_gates_card_id'), ['card_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kanban_gates_project_key'), ['project_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_kanban_gates_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kanban_gates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kanban_gates_status'))
        batch_op.drop_index(batch_op.f('ix_kanban_gates_project_key'))
        batch_op.drop_index(batch_op.f('ix_kanban_gates_card_id'))

    op.drop_table('kanban_gates')
    with op.batch_alter_table('kanban_deliverables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kanban_deliverables_card_id'))

    op.drop_table('kanban_deliverables')
    with op.batch_alter_table('kanban_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kanban_attachments_card_id'))

    op.drop_table('kanban_attachments')
    with op.batch_alter_table('kanban_work_type_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kanban_work_type_mappings_project_key'))

    op.drop_table('kanban_work_type_mappings')
    with op.batch_alter_table('kanban_ops', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kanban_ops_project_key'))
        batch_op.drop_index(batch_op.f('ix_kanban_ops_hlc'))
        batch_op.drop_index(batch_op.f('ix_kanban_ops_entity_id'))
        batch_op.drop_index(batch_op.f('ix_kanban_ops_device_id'))

    op.drop_table('kanban_ops')
    op.drop_table('kanban_meta')
    with op.batch_alter_table('kanban_columns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kanban_columns_project_key'))

    op.drop_table('kanban_columns')
    with op.batch_alter_table('kanban_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kanban_cards_project_key'))
        batch_op.drop_index(batch_op.f('ix_kanban_cards_parent_card_id'))

    op.drop_table('kanban_cards')
    # ### end Alembic commands ###
